starting from the zbar setup

diff --git a/bin/compile b/bin/compile
--- a/bin/compile
+++ b/bin/compile
@@ -1,46 +1,55 @@
 #!/usr/bin/env bash
-# bin/compile <build-dir> <cache-dir>
 
-# fail fast
-set -e
+# set -e            # fail fast
+# set -o pipefail   # don't ignore exit codes when piping output
+# set -x          # enable debugging
 
-# debug
-# set -x
+# Configure directories
+build_dir=$1
+cache_dir=$2
+env_dir=$3
 
-# parse and derive params
-BUILD_DIR=$1
-CACHE_DIR=$2
-LP_DIR=`cd $(dirname $0); cd ..; pwd`
+bp_dir=$(cd $(dirname $0); cd ..; pwd)
 
-mkdir -p "$1/bin/"
+source $bp_dir/bin/common.sh
 
-function error() {
-  echo " !     $*" >&2
-  exit 1
+# export LDFLAGS=-L$build_dir/vendor/lib
+# export LD_LIBRARY_PATH=$build_dir/vendor/lib
+
+download () {
+  status "Downloading and installing wkhtmltopdf"
+  wkhtmltopdf_url="https://codeload.github.com/wkhtmltopdf/wkhtmltopdf/tar.gz/0.12.1"
+  curl $wkhtmltopdf_url -s -o - | tar xzvf - -C $build_dir
 }
 
-function topic() {
-  echo "-----> $*"
+install () {
+	if [ -f $build_dir/vendor/wkhtmltopdf ]; then
+	  exit 0
+	else
+	  download
+  	  mkdir -p $build_dir/vendor/bin
+	  mv $build_dir/0.12.1 $build_dir/vendor/wkhtmltopdf
+	  cd $build_dir/vendor/wkhtmltopdf
+	  status "Configuring wkhtmltopdf"
+	  ./configure   >/dev/null 2>&1
+	  status "Make!"
+	  make  >/dev/null 2>&1
+	  status "Make install !!!"
+	  make install  >/dev/null 2>&1
+	fi
 }
 
-function indent() {
-  c='s/^/       /'
-  case $(uname) in
-	Darwin) sed -l "$c";;
-	*)      sed -u "$c";;
-  esac
-}
 
-WKHTMLTOPDF_SOURCE="http://ubuntu.cs.utah.edu/ubuntu/pool/universe/w/wkhtmltopdf/wkhtmltopdf_0.12.0-2_amd64.deb"
-WKHTMLTOPDF_PATH="$1/bin/wkhtmltopdf_0.12.0-2_amd64.deb"
+install
 
-echo "-----> Transferring wkhtmltopdf binary"
-curl $WKHTMLTOPDF_SOURCE -o $WKHTMLTOPDF_PATH
+status "Writing profile script"
+mkdir -p $build_dir/.profile.d
+cat <<EOF >$build_dir/.profile.d/000_wkhtmltopdf.sh
+export PATH="\$HOME/vendor/bin$PATH"
+export LD_LIBRARY_PATH="\$HOME/vendor/lib:\$LD_LIBRARY_PATH"
+export INCLUDE_PATH="\$HOME/vendor/include:\$INCLUDE_PATH"
+export CPATH="\$INCLUDE_PATH"
+export CPPPATH="\$INCLUDE_PATH"
+EOF
 
-echo "-----> Setting permissions"
-chmod +x $WKHTMLTOPDF_PATH
-
-echo "-----> Extracting Debs"
-ar x  "$1/bin/wkhtmltopdf_0.12.0-2_amd64.deb"
-
-export HOME=$BUILD_DIR
+exit 0
